apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: app
images:
  - name: ghcr.io/OWNER/REPO
    newName: ghcr.io/OWNER/REPO
    newTag: placeholder # {"$imagepolicy": "flux-system:app-production:tag"}
