apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: app
images:
  - name: ghcr.io/steve-todorov/bdk3
    newName: ghcr.io/steve-todorov/bdk3
    newTag: production-4-1781139721 # {"$imagepolicy": "flux-system:app-production:tag"}
