apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: app-prs
  namespace: flux-system
spec:
  type: GitHubPullRequest
  url: https://github.com/steve-todorov/bdk3
  schedule:
    - cron: "*/1 * * * *"
  filter:
    labels: ["preview"]
  secretRef:
    name: github-token
