apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app
  namespace: flux-system
spec:
  url: https://github.com/steve-todorov/bdk3
  secretRef:
    name: flux-git-auth
  ref:
    branch: main
  interval: 1m
